### ISSUE TITLE
[rbac-manager] Add ServiceMonitor for prometheus scraping

### ISSUE THREAD

**Issue by ryan-dyer-sp** [FairwindsOps/charts#391]
**Is your feature request related to a problem? Please describe.**
I would like the helm chart for rbac-manager to include a headless service and prometheus operator servicemonitor to make the full integration experience with rbac-manager and monitoring smoother.  Currently we install rbac-manager via helm and then have to apply a service and servicemonitor manifest with the correct labels. As we don't control all of the labels used by the helm chart, any updates to these labels can result in needing to also update the service and servicemonitor.

I am happy to provide a PR with functionality if this is something that would be accepted.  I have found that the inclusion of these varies per OSS project (grafana, KIAM, and external-dns to name a few that do) while others choose not to as a ServiceMonitor is not a native k8s construct. 

Assuming this is something that would be approved are the following additions to the values.yaml acceptable:
```
monitoring:
  enabled: <true|false(default)>
  namespace: <"" | namespace> # defaults to "" / namespace the rbac-manager is installed into.  however some like to keep the servicemonitors in a different namespace>
  interval: 60s 
  # normally path and port are customizable here as well, but it appears you have the port and paths currently hard coded to 8080 and /metrics so I would leave those as they are.  
```

Please let me know.  Thanks,
Ryan
